import java.io.Serializable;
import java.util.HashMap;


public class MessagePacket implements Serializable {
	
	
	/* -------------------- MESSAGE TYPES --------------------- */
	/* Send from client to server */
	public static final int ADMIN_MESSAGE_TYPE_JOIN_GAME_REQUEST = 100; 
	
	/* Send from server to client for join request */ 
	public static final int ADMIN_MESSAGE_TYPE_JOIN_GAME_SUCCESS = 101; 
	
	/* Send from server to client for join request */
	public static final int ADMIN_MESSAGE_TYPE_JOIN_GAME_FAILURE = 102;
	
	/* 
	 * Broadcast from server to clients. 
	 * This message is also used for setting up clients with initial game status
	 * Using 
	 * 	- playerLocations  
	 */
	static final int ADMIN_MESSAGE_TYPE_GAME_START = 200; 
	
	/*
	 * Spawn playerName on point
	 * Using following optional fields:
	 * 	- playerName
	 * 	- point
	 */
	public static final int GAME_MESSAGE_TYPE_SPAWN_PLAYER = 300;
	
	/*
	 * Game message generated by clients' keypress
	 * Using following optional fields:
	 * 	- playerName
	 * 
	 */
	public static final int GAME_MESSAGE_TYPE_MOVE_PLAYER_FORWARD = 301;
	
	public static final int GAME_MESSAGE_TYPE_MOVE_PLAYER_BACKWARD = 302;
	
	public static final int GAME_MESSAGE_TYPE_TURN_LEFT = 304;
	
	public static final int GAME_MESSAGE_TYPE_TURN_RIGHT = 305;
	
	public static final int GAME_MESSAGE_TYPE_FIRE = 306;
	
	
	public static final int ERROR_REASON_PLAYERNAME_EXISTS = 0;
	public static final int ERROR_REASON_SERVER_FULL = 1;
	
	/* -------------------- MESSAGE FIELDS --------------------- */
	

	
	/* Mandatory Field */
	public int messageType; /* Either ADMIN_MESSAGE_TYPE or GAME_MESSAGE_TYPE defined above */
	
	public int seqNo; /* Sequence Number for this message - set by server */
	
	/* Optional Field */
	public int reason;
	public String playerName; /* Represents player who sent the message */
	HashMap<String, Point> playerLocations;
	public Point point;

}
